# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: trusty
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    recipients:
      - 130s@2000.jukuin.keio.ac.jp
env:
  matrix:
    - ROS_DISTRO=lunar ROS_REPO=ros              UPSTREAM_WORKSPACE=moveit.rosinstall
    - ROS_DISTRO=lunar ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=moveit.rosinstall
    - ROS_DISTRO=lunar TEST=clang-format         UPSTREAM_WORKSPACE=moveit.rosinstall
    - ROS_DISTRO=lunar PRERELEASE=true           UBUNTU_OS_CODE_NAME="zesty"
before_script:
  - git clone -q https://github.com/ros-industrial/industrial_ci.git .moveit_ci
script:
  - source .moveit_ci/travis.sh